version: '3'
services:
  dev:
    image: '${BASE_IMAGE}:dev'
    build:
      context: .
      args:
        DEBIAN_VERSION: '${DEBIAN_VERSION:-stretch}'
  prod:
    image: '${BASE_IMAGE}:${TAG}'
    build:
      context: .
      args:
        DEBIAN_VERSION: "${DEBIAN_VERSION:-stretch-slim}"
